"""Add Product

Revision ID: 271a1ccf78cc
Revises: 79eb6d647366
Create Date: 2025-12-15 13:17:54.063078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271a1ccf78cc'
down_revision = '79eb6d647366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
