"""Add category

Revision ID: bd9897089f6e
Revises: 271a1ccf78cc
Create Date: 2025-12-15 13:25:53.680374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9897089f6e'
down_revision = '271a1ccf78cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('category_id', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('categories')

    op.drop_table('categories')
    # ### end Alembic commands ###
