"""add active column to products

Revision ID: f8f7e2d9ba96
Revises: efa541a6fd37
Create Date: 2025-12-15 15:07:41.070500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f7e2d9ba96'
down_revision = 'efa541a6fd37'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa

def upgrade():
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column("active", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
